# Embedded file name: scripts/common/Dialog.py
"""
Created on 02.03.2011

@author: Madcat
"""
EVENT_TYPE_TRADE = 1
EVENT_TYPE_CHANGE = 2
EVENT_TYPE_CREATECLAN = 3
EVENT_TYPE_REPAIR = 4
EVENT_TYPE_TELEPORT = 5
EVENT_TYPE_COMPLEX_REPAIR = 6
EVENT_TYPE_BARTER = 7
EVENT_TYPE_TELEPORT_TO_CLAN_BASE = 8
EVENT_TYPE_GO_PVP_AREA = 9
EVENT_TYPE_START_PVP = 10
GET_WITH_CHECK = 0
GET = 1
TEST_TYPE_CLAN = 0
TEST_TYPE_CLAN_ID = 1
TEST_TYPE_NOT_IN_CLAN = 2