# Embedded file name: scripts/common/FiringDefs.py
"""
Created on 21.07.2010

@author: leviathan
"""
from Config.Damage import DamageTypes, BODY_ZONES

class FiringDefs(object):
    ACCURACY_PERCENT_MOD = 1000.0
    globalDamageMultiplier = 1.0
    MAX_RECOIL_VALUE = 0.3
    STRONGEST_KICKBACK = MAX_RECOIL_VALUE / 3.0
    PITCH_BORDER_VALUE = 1.0
    UPDATE_LOOK_TEMER_PERIOD = 0.1
    KICKBACK_UPDATE_RATE = UPDATE_LOOK_TEMER_PERIOD
    KIKCBACK_RECOVERY_RATE = 4.0
    DEF_CLOSE_MAX = 0.9
    DEF_FAR_MAX = 2.0
    DEF_HORIZONTAL = 0.35
    DEF_VERTICAL = 1.6
    LOOKINGAROUND_FAR_MAX = 2.2
    LOOKINGAROUND_ZOOMED_MAX = 7.0
    LOOKINGAROUND_HORIZONTAL = 0
    LOOKINGAROUND_VERTICAL = 1.2
    SITTING_FAR_MAX = 1.0
    SITTING_HORIZONTAL = LOOKINGAROUND_HORIZONTAL
    SITTING_VERTICAL = 0.9
    LOOKINGAROUND_AND_SITTING_FAR_MAX = LOOKINGAROUND_FAR_MAX
    LOOKINGAROUND_AND_SITTING_HORIZONTAL = LOOKINGAROUND_HORIZONTAL
    LOOKINGAROUND_AND_SITTING_VERTICAL = 0.7
    SNIPING_HORIZONTAL = 0
    SNIPING_VERTICAL = 1.0
    CLOSE_PIVOT_MAX_DIST = DEF_CLOSE_MAX
    FAR_PIVOT_MAX_DIST = DEF_FAR_MAX
    CAMERA_PIVOT_HORIZONTAL_SHIFT = DEF_HORIZONTAL
    CAMERA_PIVOT_VERTICAL_SHIFT = DEF_VERTICAL
    CAMERA_PIVOT_VERTICAL_SHIFT_SITTING = 1.15
    SNIPER_SCOPE_KOEFF = 0.1
    BASE_PENETRATION = 100.0
    DAMAGE_NORMAL, DAMAGE_CRITICAL = xrange(2)
    NO_ITEM_EQUIPPED, MODEL_NOT_READY, NOT_A_WEAPON, NO_AMMO, WEAPON_JAMMED, WEAPON_READY = xrange(6)
    GUN_FIRE_SOUND_RADIUS = 20.0
    DAMAGE_RANGES = [20.0,
     40.0,
     80.0,
     140.0]


for name, val in BODY_ZONES.__dict__.iteritems():
    if not name.startswith('__'):
        setattr(FiringDefs, name, val)