# Embedded file name: scripts/common/heads.py
from Items import ItemBase
key = ItemBase.HEAD
gui_key = '01_head'
presets = [{'head_id': 1,
  'model': 'characters/avatars/heads/head_m5_01.model',
  'tint': {},
  'attachments': []},
 {'head_id': 2,
  'model': 'characters/avatars/heads/head_m5_02.model',
  'tint': {},
  'attachments': []},
 {'head_id': 3,
  'model': 'characters/avatars/heads/head_m5_03.model',
  'tint': {},
  'attachments': []},
 {'head_id': 4,
  'model': 'characters/avatars/heads/head_m5_04.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_04_beard.model',
                   'tint': {},
                   'att_type': ItemBase.MASK}]},
 {'head_id': 5,
  'model': 'characters/avatars/heads/head_m5_05.model',
  'tint': {},
  'attachments': []},
 {'head_id': 6,
  'model': 'characters/avatars/heads/head_m5_06_bandit.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_06_bandit_beard.model',
                   'tint': {},
                   'att_type': ItemBase.MASK}]},
 {'head_id': 7,
  'model': 'characters/avatars/heads/head_m5_07.model',
  'tint': {},
  'attachments': []},
 {'head_id': 8,
  'model': 'characters/avatars/heads/head_m5_08.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_08_beard.model',
                   'tint': {},
                   'att_type': ItemBase.MASK}]},
 {'head_id': 9,
  'model': 'characters/avatars/heads/head_m5_09.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_09_hair.model',
                   'tint': {},
                   'att_type': ItemBase.HAT}]},
 {'head_id': 10,
  'model': 'characters/avatars/heads/head_m5_10.model',
  'tint': {},
  'attachments': []},
 {'head_id': 11,
  'model': 'characters/avatars/heads/head_m5_11.model',
  'tint': {},
  'attachments': []},
 {'head_id': 12,
  'model': 'characters/avatars/heads/head_m5_12.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_12_hair.model',
                   'tint': {},
                   'att_type': ItemBase.HAT}]},
 {'head_id': 13,
  'model': 'characters/avatars/heads/head_m5_13.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_13_hair.model',
                   'tint': {},
                   'att_type': ItemBase.MASK}]},
 {'head_id': 14,
  'model': 'characters/avatars/heads/head_m5_14.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_14_hair.model',
                   'tint': {},
                   'att_type': ItemBase.MASK}]},
 {'head_id': 15,
  'model': 'characters/avatars/heads/head_m5_15.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_15_hair.model',
                   'tint': {},
                   'att_type': ItemBase.HAT}]},
 {'head_id': 16,
  'model': 'characters/avatars/heads/head_m5_16.model',
  'tint': {},
  'attachments': []},
 {'head_id': 17,
  'model': 'characters/avatars/heads/head_m5_17.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_17_hair.model',
                   'tint': {},
                   'att_type': ItemBase.HAT}]},
 {'head_id': 18,
  'model': 'characters/avatars/heads/head_m5_18.model',
  'tint': {},
  'attachments': []},
 {'head_id': 19,
  'model': 'characters/avatars/heads/head_m5_19.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_19_hair.model',
                   'tint': {},
                   'att_type': ItemBase.MASK}]},
 {'head_id': 20,
  'model': 'characters/avatars/heads/head_m5_20.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_20_hair.model',
                   'tint': {},
                   'att_type': ItemBase.MASK}]},
 {'head_id': 21,
  'model': 'characters/avatars/heads/head_m5_21.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_21_hair.model',
                   'tint': {},
                   'att_type': ItemBase.MASK}]},
 {'head_id': 22,
  'model': 'characters/avatars/heads/head_m5_22_bandit.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_22_hair.model',
                   'tint': {},
                   'att_type': ItemBase.HAT}]},
 {'head_id': 23,
  'model': 'characters/avatars/heads/head_m5_26.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_26_hair.model',
                   'tint': {},
                   'att_type': ItemBase.HAT}]},
 {'head_id': 24,
  'model': 'characters/avatars/heads/head_m5_27.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_27_dreadlocks.model',
                   'tint': {},
                   'att_type': ItemBase.HAT}]},
 {'head_id': 25,
  'model': 'characters/avatars/heads/head_m5_28.model',
  'tint': {},
  'attachments': [{'model': 'characters/avatars/heads/custom/head_m5_28_hair.model',
                   'tint': {},
                   'att_type': ItemBase.MASK}]},
 {'head_id': 26,
  'model': 'characters/avatars/heads/head_m5_29.model',
  'tint': {},
  'attachments': []},
 {'head_id': 27,
  'model': 'characters/avatars/heads/head_m5_30.model',
  'tint': {},
  'attachments': []}]
preset_by_headid = dict(((p['head_id'], p) for p in presets))
default = presets[0]