# Embedded file name: scripts/common/NPCs.py
from Localization import lc
from Items import ItemsCatalog
from Config.Damage import DamageTypes
from NPCByName import npc_list

class NPCs:
    GUARDIAN, STANDING_NPC, STANDING_GUARDIAN, WALKER, FRACTION_HUNTER, STANDING_FRACTION_HUNTER, STANDING_ATTACKER, BASE_PRIVATE_1, BASE_CORPORAL_1, BASE_SERGANT_1, BASE_TEST, DONAT_GUARDIAN = xrange(12)
    donate_base_doorman, clan_warehouse, warehouse_transport, clan_trader = range(13, 17)
    BASES_NPCS = [BASE_PRIVATE_1,
     BASE_CORPORAL_1,
     BASE_SERGANT_1,
     BASE_TEST,
     DONAT_GUARDIAN]
    BaseModel = 'characters/avatars/basem.model'
    names_by_npcName = npc_list().names_by_npcName
    names_by_npcType = {GUARDIAN: lc('NPCs.common.NPC181'),
     STANDING_GUARDIAN: lc('NPCs.common.NPC182'),
     WALKER: lc('NPCs.common.NPC183'),
     BASE_PRIVATE_1: lc('NPCs.common.NPC184'),
     BASE_CORPORAL_1: lc('NPCs.common.NPC185'),
     BASE_SERGANT_1: lc('NPCs.common.NPC186'),
     BASE_TEST: lc('NPCs.common.STRING_220_12'),
     DONAT_GUARDIAN: lc('NPCs.common.STRING_221_18'),
     donate_base_doorman: lc('NPCs.common.NPC205'),
     clan_warehouse: lc('NPCs.common.NPC196'),
     warehouse_transport: lc('NPCs.common.NPC196')}
    defence_by_npcName = {}
    scale_by_npcName = {'Metrofan': 0.9,
     'Plyuch': 0.9}
    impactChance_by_npcType = {BASE_PRIVATE_1: 0.6,
     BASE_CORPORAL_1: 0.8,
     BASE_SERGANT_1: 0.9,
     BASE_TEST: 0.9,
     DONAT_GUARDIAN: 1.0}
    health_by_npcType = {BASE_PRIVATE_1: 4500.0,
     BASE_CORPORAL_1: 6000.0,
     BASE_SERGANT_1: 7500.0,
     BASE_TEST: 175.0,
     DONAT_GUARDIAN: 5000.0}
    defence_by_npcType = {GUARDIAN: {DamageTypes.BULLET: 150.0,
                DamageTypes.MELEE: 50.0},
     STANDING_GUARDIAN: {DamageTypes.BULLET: 150.0,
                         DamageTypes.MELEE: 50.0},
     WALKER: {DamageTypes.BULLET: 400.0,
              DamageTypes.MELEE: 100.0},
     STANDING_ATTACKER: {DamageTypes.BULLET: 0.0,
                         DamageTypes.MELEE: 100.0},
     BASE_PRIVATE_1: {DamageTypes.BULLET: 0.0,
                      DamageTypes.MELEE: 300.0},
     BASE_CORPORAL_1: {DamageTypes.BULLET: 0.0,
                       DamageTypes.MELEE: 300.0},
     BASE_SERGANT_1: {DamageTypes.BULLET: 0.0,
                      DamageTypes.MELEE: 400.0},
     BASE_TEST: {DamageTypes.BULLET: 400.0,
                 DamageTypes.MELEE: 100.0},
     DONAT_GUARDIAN: {DamageTypes.BULLET: 0.0,
                      DamageTypes.MELEE: 400.0}}
    damage_by_npcName = {}
    damage_by_npcType = {GUARDIAN: {'penetration': 100.0,
                'mainDamage': {DamageTypes.BULLET: (169.4, 169.4)},
                'additionalDamage': {DamageTypes.ARMOR_PIERCING: (46.3, 46.3)}},
     STANDING_GUARDIAN: {'penetration': 100.0,
                         'mainDamage': {DamageTypes.BULLET: (169.4, 169.4)},
                         'additionalDamage': {DamageTypes.ARMOR_PIERCING: (46.3, 46.3)}},
     STANDING_FRACTION_HUNTER: {'penetration': 100.0,
                                'mainDamage': {DamageTypes.BULLET: (10.4, 16.4)},
                                'additionalDamage': {DamageTypes.ARMOR_PIERCING: (4.3, 6.3)}},
     FRACTION_HUNTER: {'penetration': 100.0,
                       'mainDamage': {DamageTypes.BULLET: (10.4, 16.4)},
                       'additionalDamage': {DamageTypes.ARMOR_PIERCING: (4.3, 6.3)}},
     WALKER: {'penetration': 100.0,
              'mainDamage': {DamageTypes.BULLET: (52.2, 63.8)},
              'additionalDamage': {DamageTypes.ARMOR_PIERCING: (55.1, 60.9)}},
     STANDING_ATTACKER: {'penetration': 100.0,
                         'mainDamage': {DamageTypes.BULLET: (10.0, 20.0)},
                         'additionalDamage': {DamageTypes.ARMOR_PIERCING: (3.0, 7.0)}},
     BASE_PRIVATE_1: {'penetration': 100.0,
                      'mainDamage': {DamageTypes.BULLET: (20.5, 25.5)},
                      'ditionalDamage': {DamageTypes.ARMOR_PIERCING: (5.5, 7.5)}},
     BASE_CORPORAL_1: {'penetration': 100.0,
                       'mainDamage': {DamageTypes.BULLET: (30.5, 40.5)},
                       'additionalDamage': {DamageTypes.ARMOR_PIERCING: (10.5, 15.5)}},
     BASE_SERGANT_1: {'penetration': 100.0,
                      'mainDamage': {DamageTypes.BULLET: (45.5, 50.5)},
                      'additionalDamage': {DamageTypes.ARMOR_PIERCING: (15.5, 20.5)}},
     BASE_TEST: {'penetration': 100.0,
                 'mainDamage': {DamageTypes.BULLET: (20.5, 25.5)},
                 'additionalDamage': {DamageTypes.ARMOR_PIERCING: (5.5, 7.5)}},
     DONAT_GUARDIAN: {'penetration': 100.0,
                      'mainDamage': {DamageTypes.BULLET: (1000.0, 1000.5)},
                      'additionalDamage': {DamageTypes.ARMOR_PIERCING: (1000.5, 1000.5)}}}
    FLAG_CAN_TALK = 1
    FLAG_QUESTGIVER = 2
    FLAG_NIGHT_HIGHLIGHT = 4
    FLAG_CAN_TRADE = 8

    class Weapons:
        none, autogun_fnfal, autogun_ak47 = xrange(3)
        weapon_items = {none: None,
         autogun_fnfal: ItemsCatalog.FN_FAL_ASSAULT_RIFLE,
         autogun_ak47: ItemsCatalog.AK_47_ASSAULT_RIFLE}
        tint_weapon = {none: ''}

    class Hands:
        none, hand_koja, hand_koja_m2_poluperchatki, hand_koja_m3_poluperchatki2, hand_koja_m4_usilennie, hand_koja_m1_perch, hand_npc_hunter, hands_npc_bandit = xrange(8)
        models = {none: 'characters/avatars/basem_void.model',
         hand_koja: 'characters/avatars/hands/hand_koja.model',
         hand_koja_m2_poluperchatki: 'characters/avatars/hands/hand_koja.model',
         hand_koja_m3_poluperchatki2: 'characters/avatars/hands/hand_koja.model',
         hand_koja_m4_usilennie: 'characters/avatars/hands/hand_koja.model',
         hand_koja_m1_perch: 'characters/avatars/hands/hand_koja.model',
         hand_npc_hunter: 'characters/avatars/suite/npc_hunter/hand_npc_hunter.model',
         hands_npc_bandit: 'characters/avatars/hands/hands_bandit.model'}
        tint_hand = {none: '',
         hand_koja: '',
         hand_koja_m2_poluperchatki: 'm2_poluperchatki',
         hand_koja_m3_poluperchatki2: 'm3_poluperchatki2',
         hand_koja_m4_usilennie: 'm4_usilennie',
         hand_koja_m1_perch: 'm1_perch',
         hand_npc_hunter: '',
         hands_npc_bandit: ''}

    class Boots:
        none, boots_botinok, boots_bertsi, boots_bertsi_m2, boots_bertsi_m3, boots_bertsi_m4, boots_bertsi_m1 = xrange(7)
        models = {none: 'characters/avatars/basem_void.model',
         boots_botinok: 'characters/avatars/boots/boots_botinok.model',
         boots_bertsi: 'characters/avatars/boots/boots_bertsi.model',
         boots_bertsi_m2: 'characters/avatars/boots/boots_bertsi.model',
         boots_bertsi_m3: 'characters/avatars/boots/boots_bertsi.model',
         boots_bertsi_m4: 'characters/avatars/boots/boots_bertsi.model',
         boots_bertsi_m1: 'characters/avatars/boots/boots_bertsi.model'}
        tint_boots = {none: '',
         boots_botinok: '',
         boots_bertsi: '',
         boots_bertsi_m2: 'm2',
         boots_bertsi_m3: 'm3',
         boots_bertsi_m4: 'm4',
         boots_bertsi_m1: 'm1'}

    class Bodies:
        body_shtormovka, body_spetsovka, body_haki, body_pilot, body_chak, body_shtormovka_woh, body_shiz, body_haki_woh, body_harvat, body_kurtka, body_partizan, body_spetsovka_woh, body_uniform, body_uniform_science, body_uniform, body_uniform_technical, body_uniform, body_uniform_medical, suite_pachka, suite_mars, suite_ugory, suite_voenstal, suite_sigma, suite_dsc, suite_redcross, suite_pps, suite_mask_snipe, suite_svoboda, suite_clan_inquisitor, suite_clan_predator, suite_svoboda, suite_clan_silence, suite_single, suite_npc_scientist, suite_npc_alkash, suite_npc_pomogalo, suite_npc_otshelnik, suite_npc_military_face, suite_npc_military_mask, suite_npc_military, body_npc_hunter, suite_npc_bandit_masterka, suite_npc_bandit_sw_red, suite_npc_bandit_sw_green, suite_npc_bandit_sw_gray, suite_npc_torgovez, suite_clan_stels, suite_robe_01, suite_robe_01_medic, suite_robe_01_scientist, suite_robe_01_technician, grandma_01, pilot_01, pilot_02, boatswain_body_01, arab_body, arab_bek, mechanic, fanatic = xrange(59)
        models = {body_shtormovka: 'characters/avatars/body/body_shtormovka.model',
         body_spetsovka: 'characters/avatars/body/body_spetsovka.model',
         body_haki: 'characters/avatars/body/body_haki.model',
         body_pilot: 'characters/avatars/body/body_pilot.model',
         body_chak: 'characters/avatars/body/body_chak.model',
         body_shtormovka_woh: 'characters/avatars/body/body_shtormovka_woh.model',
         body_shiz: 'characters/avatars/body/body_shiz.model',
         body_haki_woh: 'characters/avatars/body/body_haki_woh.model',
         body_harvat: 'characters/avatars/body/body_harvat.model',
         body_kurtka: 'characters/avatars/body/body_kurtka.model',
         body_partizan: 'characters/avatars/body/body_partizan.model',
         body_spetsovka_woh: 'characters/avatars/body/body_spetsovka_woh.model',
         body_uniform: 'characters/avatars/body/body_uniform.model',
         body_uniform_science: 'characters/avatars/body/body_uniform.model',
         body_uniform: 'characters/avatars/body/body_uniform.model',
         body_uniform_technical: 'characters/avatars/body/body_uniform.model',
         body_uniform: 'characters/avatars/body/body_uniform.model',
         body_uniform_medical: 'characters/avatars/body/body_uniform.model',
         suite_pachka: 'characters/avatars/suite/suite_pachka.model',
         suite_mars: 'characters/avatars/suite/suite_mars.model',
         suite_ugory: 'characters/avatars/suite/suite_ugory.model',
         suite_voenstal: 'characters/avatars/suite/suite_voenstal.model',
         suite_sigma: 'characters/avatars/suite/suite_sigma.model',
         suite_dsc: 'characters/avatars/suite/suite_dsc.model',
         suite_redcross: 'characters/avatars/suite/suite_red-cross.model',
         suite_pps: 'characters/avatars/suite/suite_pps.model',
         suite_mask_snipe: 'characters/avatars/suite/suite_mask_snipe.model',
         suite_svoboda: 'characters/avatars/suite/suite_svoboda.model',
         suite_clan_inquisitor: 'characters/avatars/suite/suite_clan_inquisitor.model',
         suite_clan_predator: 'characters/avatars/suite/suite_clan_predator.model',
         suite_svoboda: 'characters/avatars/suite/suite_svoboda.model',
         suite_clan_silence: 'characters/avatars/suite/suite_clan_silence.model',
         suite_single: 'characters/avatars/suite/suite_single.model',
         suite_npc_scientist: 'characters/avatars/suite/suite_npc_scientist.model',
         suite_npc_alkash: 'characters/npc/alkash/alkash.model',
         suite_npc_pomogalo: 'characters/npc/pomogalo/pomogalo.model',
         suite_npc_otshelnik: 'characters/npc/otshelnik/otshelnik.model',
         suite_npc_military_face: 'characters/avatars/suite/suite_npc_military_f.model',
         suite_npc_military_mask: 'characters/avatars/suite/suite_npc_military_m.model',
         suite_npc_military: 'characters/avatars/suite/suite_npc_military.model',
         body_npc_hunter: 'characters/avatars/suite/npc_hunter/body_npc_hunter.model',
         suite_npc_bandit_masterka: 'characters/avatars/body/body_bandit.model',
         suite_npc_bandit_sw_red: 'characters/avatars/body/body_bandit.model',
         suite_npc_bandit_sw_green: 'characters/avatars/body/body_bandit.model',
         suite_npc_bandit_sw_gray: 'characters/avatars/body/body_bandit.model',
         suite_npc_torgovez: 'characters/npc/torgovez/npc_torgovez.model',
         suite_clan_stels: 'characters/avatars/suite/suite_clan_stels.model',
         suite_robe_01: 'characters/avatars/suite/suite_robe_01.model',
         suite_robe_01_medic: 'characters/avatars/suite/suite_robe_01_medic.model',
         suite_robe_01_scientist: 'characters/avatars/suite/suite_robe_01_scientist.model',
         suite_robe_01_technician: 'characters/avatars/suite/suite_robe_01_technician.model',
         grandma_01: 'characters/npc/grandma/grandma_01.model',
         pilot_01: 'characters/npc/pilot/pilot_01.model',
         pilot_02: 'characters/npc/pilot/pilot_02.model',
         boatswain_body_01: 'characters/npc/boatswain/boatswain_body_01.model',
         arab_body: 'characters/npc/arab/arab_guard_01_body.model',
         arab_bek: 'characters/npc/arab_bek/arab_bek_01.model',
         mechanic: 'characters/npc/mechanic/mechanic_01.model',
         fanatic: 'characters/npc/businessman/businessman_01.model'}
        tint_body = {body_shtormovka: '',
         body_spetsovka: '',
         body_haki: '',
         body_pilot: '',
         body_chak: '',
         body_shtormovka_woh: '',
         body_shiz: '',
         body_haki_woh: '',
         body_harvat: '',
         body_kurtka: '',
         body_partizan: '',
         body_spetsovka_woh: '',
         body_uniform: '',
         body_uniform_science: 'science',
         body_uniform: '',
         body_uniform_technical: 'technical',
         body_uniform: '',
         body_uniform_medical: 'medical',
         suite_pachka: '',
         suite_mars: '',
         suite_ugory: '',
         suite_voenstal: '',
         suite_sigma: '',
         suite_dsc: '',
         suite_redcross: '',
         suite_pps: '',
         suite_mask_snipe: '',
         suite_svoboda: '',
         suite_clan_inquisitor: '',
         suite_clan_predator: '',
         suite_svoboda: '',
         suite_clan_silence: '',
         suite_single: '',
         suite_npc_scientist: '',
         suite_npc_alkash: '',
         suite_npc_pomogalo: '',
         suite_npc_otshelnik: '',
         suite_npc_military_face: '',
         suite_npc_military_mask: '',
         suite_npc_military: '',
         body_npc_hunter: '',
         suite_npc_bandit_masterka: '',
         suite_npc_bandit_sw_red: 'sweater_red',
         suite_npc_bandit_sw_green: 'sweater_green',
         suite_npc_bandit_sw_gray: 'sweater_gray',
         suite_npc_torgovez: '',
         suite_clan_stels: '',
         suite_robe_01: '',
         suite_robe_01_medic: '',
         suite_robe_01_scientist: '',
         suite_robe_01_technician: '',
         grandma_01: '',
         pilot_01: '',
         pilot_02: '',
         boatswain_body_01: ''}

    class Armors:
        none, armor_ninja, armor_kaiser, armor_dragoon, armor_fauna, armor_chak, armor_flora, armor_mayka, armor_omelet, armor_rat, armor_sandal, armor_shkurka, armor_shpinat, armor_suhar, armor_tash, armor_vorot, armor_npc_bandit, armor_npc_hunter, arab_jacket, arab_vest = xrange(20)
        models = {none: 'characters/avatars/basem_void.model',
         armor_ninja: 'characters/avatars/mod-armor/armor_ninja.model',
         armor_kaiser: 'characters/avatars/mod-armor/armor_kaiser.model',
         armor_dragoon: 'characters/avatars/mod-armor/armor_dragoon.model',
         armor_fauna: 'characters/avatars/mod-armor/armor_fauna.model',
         armor_chak: 'characters/avatars/mod-armor/armor_chak.model',
         armor_flora: 'characters/avatars/mod-armor/armor_flora.model',
         armor_mayka: 'characters/avatars/mod-armor/armor_mayka.model',
         armor_omelet: 'characters/avatars/mod-armor/armor_omelet.model',
         armor_rat: 'characters/avatars/mod-armor/armor_rat.model',
         armor_sandal: 'characters/avatars/mod-armor/armor_sandal.model',
         armor_shkurka: 'characters/avatars/mod-armor/armor_shkurka.model',
         armor_shpinat: 'characters/avatars/mod-armor/armor_shpinat.model',
         armor_suhar: 'characters/avatars/mod-armor/armor_suhar.model',
         armor_tash: 'characters/avatars/mod-armor/armor_tash.model',
         armor_vorot: 'characters/avatars/mod-armor/armor_vorot.model',
         armor_npc_bandit: 'characters/avatars/mod-armor/armor_bandit.model',
         armor_npc_hunter: 'characters/avatars/suite/npc_hunter/armor_npc_hunter.model',
         arab_jacket: 'characters/npc/arab/arab_guard_01_jacket.model',
         arab_vest: 'characters/npc/arab/arab_guard_01_vest.model'}
        tint_armor = {none: '',
         armor_ninja: '',
         armor_kaiser: '',
         armor_dragoon: '',
         armor_fauna: '',
         armor_chak: '',
         armor_flora: '',
         armor_mayka: '',
         armor_omelet: '',
         armor_rat: '',
         armor_sandal: '',
         armor_shkurka: '',
         armor_shpinat: '',
         armor_suhar: '',
         armor_tash: '',
         armor_vorot: '',
         armor_npc_bandit: '',
         armor_npc_hunter: ''}

    class Legs:
        none, legs_djinsy, legs_longi, legs_chak, legs_shiz, legs_haki, legs_harvat, legs_partizan, legs_npc_hunter_forest, legs_npc_hunter_swamp, legs_npc_bandit, boatswain_legs_01 = xrange(12)
        models = {none: 'characters/avatars/basem_void.model',
         legs_djinsy: 'characters/avatars/legs/legs_djinsy.model',
         legs_longi: 'characters/avatars/legs/legs_longi.model',
         legs_chak: 'characters/avatars/legs/legs_chak.model',
         legs_shiz: 'characters/avatars/legs/legs_shiz.model',
         legs_haki: 'characters/avatars/legs/legs_haki.model',
         legs_harvat: 'characters/avatars/legs/legs_harvat.model',
         legs_partizan: 'characters/avatars/legs/legs_partizan.model',
         legs_npc_hunter_forest: 'characters/avatars/suite/npc_hunter/legs_npc_hunter_forest.model',
         legs_npc_hunter_swamp: 'characters/avatars/suite/npc_hunter/legs_npc_hunter_swamp.model',
         legs_npc_bandit: 'characters/avatars/legs/legs_bandit.model',
         boatswain_legs_01: 'characters/npc/boatswain/boatswain_legs_01.model'}
        tint_legs = {none: '',
         legs_djinsy: '',
         legs_longi: '',
         legs_chak: '',
         legs_shiz: '',
         legs_haki: '',
         legs_harvat: '',
         legs_partizan: '',
         legs_npc_hunter_forest: '',
         legs_npc_hunter_swamp: '',
         legs_npc_bandit: '',
         boatswain_legs_01: ''}

    class Caps:
        none, cap_viking, cap_pitorka, cap_panama, cap_beret, cap_kozir, cap_mazay_04, helm_scientist_chrome, helm_scientist_blue, helm_scientist_white, head_m5_12_hair, head_m5_26_hair, cap_bandit_01, cap_bandit_02, cap_bandit_03, cap_npc_hunter_koz, cap_npc_hunter_shap, boatswain_cap_01, turban01, turban02, turban03, turban04 = xrange(22)
        models = {none: '',
         cap_viking: 'characters/avatars/mod-cap/cap_viking.model',
         cap_pitorka: 'characters/avatars/mod-cap/cap_pitorka.model',
         cap_panama: 'characters/avatars/mod-cap/cap_panama.model',
         cap_beret: 'characters/avatars/mod-cap/cap_beret.model',
         cap_kozir: 'characters/avatars/mod-cap/cap_kozir.model',
         cap_mazay_04: 'characters/avatars/mod-cap/cap_mazay_04_lod1.model',
         helm_scientist_chrome: 'characters/avatars/heads/helm_npc_scientist.model',
         helm_scientist_blue: 'characters/avatars/heads/helm_npc_scientist.model',
         helm_scientist_white: 'characters/avatars/heads/helm_npc_scientist.model',
         head_m5_12_hair: 'characters/avatars/heads/custom/head_m5_12_hair.model',
         head_m5_26_hair: 'characters/avatars/heads/custom/head_m5_26_hair.model',
         cap_bandit_01: 'characters/avatars/mod-cap/cap_bandit_01.model',
         cap_bandit_02: 'characters/avatars/mod-cap/cap_bandit_02.model',
         cap_bandit_03: 'characters/avatars/mod-cap/cap_bandit_03.model',
         cap_npc_hunter_koz: 'characters/avatars/suite/npc_hunter/cap_npc_hunter_koz.model',
         cap_npc_hunter_shap: 'characters/avatars/suite/npc_hunter/cap_npc_hunter_shap.model',
         boatswain_cap_01: 'characters/npc/boatswain/boatswain_cap_01.model',
         turban01: 'characters/npc/arab/arab_guard_01_hat_1.model',
         turban02: 'characters/npc/arab/arab_guard_01_hat_2.model',
         turban03: 'characters/npc/arab/arab_guard_01_hat_3.model',
         turban04: 'characters/npc/arab/arab_guard_01_hat_4.model'}
        tint_cap = {none: '',
         cap_viking: '',
         cap_pitorka: '',
         cap_panama: '',
         cap_beret: '',
         cap_kozir: '',
         cap_mazay_04: '',
         helm_scientist_chrome: '',
         helm_scientist_blue: 'transparent_blue',
         helm_scientist_white: 'transparent_white',
         head_m5_12_hair: '',
         head_m5_26_hair: '',
         cap_bandit_01: '',
         cap_bandit_02: '',
         cap_bandit_03: '',
         cap_npc_hunter_koz: '',
         cap_npc_hunter_shap: '',
         boatswain_cap_01: ''}

    class Masks:
        none, mask_jaba, mask_grafity, mask_bandito, mask_inglish, mask_slonik, mask_vizir, head_m5_04_beard, head_m5_06_bandit_beard, head_m5_08_beard, head_m5_27_dreadlocks, mask_glasses_circ_white, mask_glasses_circ_black, mask_glasses_rect_white, mask_glasses_rect_black, mask_glasses_kobra, grandma_01_glasses = xrange(17)
        models = {none: '',
         mask_jaba: 'characters/avatars/mod-mask/mask_jaba.model',
         mask_grafity: 'characters/avatars/mod-mask/mask_grafity.model',
         mask_bandito: 'characters/avatars/mod-mask/mask_bandito.model',
         mask_inglish: 'characters/avatars/mod-mask/mask_inglish.model',
         mask_slonik: 'characters/avatars/mod-mask/mask_slonik.model',
         mask_vizir: 'characters/avatars/mod-mask/mask_vizir.model',
         head_m5_04_beard: 'characters/avatars/heads/custom/head_m5_04_beard.model',
         head_m5_06_bandit_beard: 'characters/avatars/heads/custom/head_m5_06_bandit_beard.model',
         head_m5_08_beard: 'characters/avatars/heads/custom/head_m5_08_beard.model',
         head_m5_27_dreadlocks: 'characters/avatars/heads/custom/head_m5_27_dreadlocks.model',
         mask_glasses_circ_white: 'characters/avatars/mod-mask/mask_glasses_circ.model',
         mask_glasses_circ_black: 'characters/avatars/mod-mask/mask_glasses_circ.model',
         mask_glasses_rect_white: 'characters/avatars/mod-mask/mask_glasses_rect.model',
         mask_glasses_rect_black: 'characters/avatars/mod-mask/mask_glasses_rect.model',
         mask_glasses_kobra: 'characters/avatars/mod-mask/mask_glasses_kobra.model',
         grandma_01_glasses: 'characters/npc/grandma/grandma_01_glasses.model'}
        tint_mask = {none: '',
         mask_jaba: '',
         mask_grafity: '',
         mask_bandito: '',
         mask_inglish: '',
         mask_slonik: '',
         mask_vizir: '',
         head_m5_04_beard: '',
         head_m5_06_bandit_beard: '',
         head_m5_08_beard: '',
         head_m5_27_dreadlocks: '',
         mask_glasses_circ_white: 'white',
         mask_glasses_circ_black: 'black',
         mask_glasses_rect_white: 'white',
         mask_glasses_rect_black: 'black',
         mask_glasses_kobra: '',
         grandma_01_glasses: ''}

    class Backpacks:
        none, backpack_sakvoyaj80, backpack_kolobok, backpack_army, backpack_partizan, backpack_npc_scientist, backpack_npc_hunter_sumka, backpack_clan_chimera, backpack_single = xrange(9)
        models = {none: '',
         backpack_sakvoyaj80: 'characters/avatars/mod-back/backpack_sakvoyaj80.model',
         backpack_kolobok: 'characters/avatars/mod-back/backpack_kolobok.model',
         backpack_army: 'characters/avatars/mod-back/backpack_army.model',
         backpack_partizan: 'characters/avatars/mod-back/backpack_partizan.model',
         backpack_npc_scientist: 'characters/avatars/mod-back/backpack_npc_scientist.model',
         backpack_npc_hunter_sumka: 'characters/avatars/suite/npc_hunter/backpack_npc_hunter_sumka.model',
         backpack_clan_chimera: 'characters/avatars/mod-back/backpack_clan_chimera.model.model',
         backpack_single: 'characters/avatars/mod-back/backpack_single.model'}
        tint_back = {none: '',
         backpack_sakvoyaj80: '',
         backpack_kolobok: '',
         backpack_army: '',
         backpack_partizan: '',
         backpack_npc_scientist: '',
         backpack_npc_hunter_sumka: '',
         backpack_clan_chimera: '',
         backpack_single: ''}

    class Heads:
        none, head_m1, head_m2_02, head_m2_03, head_m2_04, head_m2_05, head_m2_05_bristle_01, head_m2_05_bristle_02, head_m2_05_bristle_03, head_m2_05_bristle_04, head_m2_05_beard_01, head_m2_05_beard_02, head_m2_05_beard_03, head_m2_05_beard_04, head_m2_05_beard_05, head_m2_06, head_m3, helm_shiz_01, helm_shiz_02, head_npc_scientist_1, head_npc_scientist_2, head_npc_scientist_3, head_m5_01, head_m5_02, head_m5_03, head_m5_04, head_m5_05, head_m5_06_bandit, head_m5_07, head_m5_08, head_m5_09, head_m5_10, head_m5_11, head_m5_12, head_m5_13, head_m5_14, head_m5_15, head_m5_16, head_m5_17, head_m5_18, head_m5_19, head_m5_20, head_m5_21, head_m5_22_bandit, head_m5_26, head_m5_27, head_m5_28, head_m5_29, head_m5_30, head_npc_military_1 = xrange(50)
        models = {none: 'characters/avatars/basem_void.model',
         head_m1: 'characters/avatars/heads/head_m5_01.model',
         head_m2_02: 'characters/avatars/heads/head_m5_02.model',
         head_m2_03: 'characters/avatars/heads/head_m5_17.model',
         head_m2_04: 'characters/avatars/heads/head_m5_04.model',
         head_m2_05: 'characters/avatars/heads/head_m5_05.model',
         head_m2_05_bristle_01: 'characters/avatars/heads/head_m5_07.model',
         head_m2_05_bristle_02: 'characters/avatars/heads/head_m5_08.model',
         head_m2_05_bristle_03: 'characters/avatars/heads/head_m5_09.model',
         head_m2_05_bristle_04: 'characters/avatars/heads/head_m5_10.model',
         head_m2_05_beard_01: 'characters/avatars/heads/head_m5_11.model',
         head_m2_05_beard_02: 'characters/avatars/heads/head_m5_12.model',
         head_m2_05_beard_03: 'characters/avatars/heads/head_m5_13.model',
         head_m2_05_beard_04: 'characters/avatars/heads/head_m5_14.model',
         head_m2_05_beard_05: 'characters/avatars/heads/head_m5_15.model',
         head_m2_06: 'characters/avatars/heads/head_m5_16.model',
         head_m3: 'characters/avatars/heads/head_m3.model',
         helm_shiz_01: 'characters/avatars/heads/helm_shiz_01_lod1.model',
         helm_shiz_02: 'characters/avatars/heads/helm_shiz_02_lod1.model',
         head_npc_scientist_1: 'characters/avatars/heads/head_npc_scientist_1.model',
         head_npc_scientist_2: 'characters/avatars/heads/head_npc_scientist_2.model',
         head_npc_scientist_3: 'characters/avatars/heads/head_npc_scientist_3.model',
         head_m5_01: 'characters/avatars/heads/head_m5_01.model',
         head_m5_02: 'characters/avatars/heads/head_m5_02.model',
         head_m5_03: 'characters/avatars/heads/head_m5_03.model',
         head_m5_04: 'characters/avatars/heads/head_m5_04.model',
         head_m5_05: 'characters/avatars/heads/head_m5_05.model',
         head_m5_06_bandit: 'characters/avatars/heads/head_m5_06_bandit.model',
         head_m5_07: 'characters/avatars/heads/head_m5_07.model',
         head_m5_08: 'characters/avatars/heads/head_m5_08.model',
         head_m5_09: 'characters/avatars/heads/head_m5_09.model',
         head_m5_10: 'characters/avatars/heads/head_m5_10.model',
         head_m5_11: 'characters/avatars/heads/head_m5_11.model',
         head_m5_12: 'characters/avatars/heads/head_m5_12.model',
         head_m5_13: 'characters/avatars/heads/head_m5_13.model',
         head_m5_14: 'characters/avatars/heads/head_m5_14.model',
         head_m5_15: 'characters/avatars/heads/head_m5_15.model',
         head_m5_16: 'characters/avatars/heads/head_m5_16.model',
         head_m5_17: 'characters/avatars/heads/head_m5_17.model',
         head_m5_18: 'characters/avatars/heads/head_m5_18.model',
         head_m5_19: 'characters/avatars/heads/head_m5_19.model',
         head_m5_20: 'characters/avatars/heads/head_m5_20.model',
         head_m5_21: 'characters/avatars/heads/head_m5_21.model',
         head_m5_22_bandit: 'characters/avatars/heads/head_m5_22_bandit.model',
         head_m5_26: 'characters/avatars/heads/head_m5_26.model',
         head_m5_27: 'characters/avatars/heads/head_m5_27.model',
         head_m5_28: 'characters/avatars/heads/head_m5_28.model',
         head_m5_29: 'characters/avatars/heads/head_m5_29.model',
         head_m5_30: 'characters/avatars/heads/head_m5_30.model',
         head_npc_military_1: 'characters/avatars/heads/head_npc_military_1.model'}
        tint_head = {none: '',
         head_m1: '',
         head_m2_02: '',
         head_m2_03: '',
         head_m2_04: '',
         head_m2_05: '',
         head_m2_05_bristle_01: '',
         head_m2_05_bristle_02: '',
         head_m2_05_bristle_03: '',
         head_m2_05_bristle_04: '',
         head_m2_05_beard_01: '',
         head_m2_05_beard_02: '',
         head_m2_05_beard_03: '',
         head_m2_05_beard_04: '',
         head_m2_05_beard_05: '',
         head_m2_06: '',
         head_m3: '',
         helm_shiz_01: '',
         helm_shiz_02: '',
         head_npc_scientist_1: '',
         head_npc_scientist_2: '',
         head_npc_scientist_3: '',
         head_m5_01: '',
         head_m5_02: '',
         head_m5_03: '',
         head_m5_04: '',
         head_m5_05: '',
         head_m5_06_bandit: '',
         head_m5_07: '',
         head_m5_08: '',
         head_m5_09: '',
         head_m5_10: '',
         head_m5_11: '',
         head_m5_12: '',
         head_m5_13: '',
         head_m5_14: '',
         head_m5_15: '',
         head_m5_16: '',
         head_m5_17: '',
         head_m5_18: '',
         head_m5_19: '',
         head_m5_20: '',
         head_m5_21: '',
         head_m5_22_bandit: '',
         head_m5_26: '',
         head_m5_27: '',
         head_m5_28: '',
         head_m5_29: '',
         head_m5_30: '',
         head_npc_military_1: ''}