# Embedded file name: scripts/common/Perks.py
from Items import ItemsCatalog

class PerkList():
    PERK_TYPE_STAT_BOOST, PERK_TYPE_SECONDARY_BOOST, PERK_TYPE_WEIGHT_REDUCERS, PERK_TYPE_RELOAD_TIME_REDUCERS, PERK_TYPE_EQUIP_TIME_REDUCERS, GAMEPLAY_CHANGERS, SUPERPERK, CRIT_DAMAGE, CRIT_CHANCE = xrange(9)
    COMBAT, SURVIVAL, OTHER = xrange(3)
    STRENGTH_BOOST = {'PerkType': 1,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'HeavyWeapon'],
                     [SURVIVAL, 'Sportsmanship'],
                     [COMBAT, 'Throwing'],
                     [OTHER, 'Packing']],
     'Type': PERK_TYPE_STAT_BOOST,
     'BoostedStat': 'Strength',
     'Value': 1,
     'NeedSkillValue': 50,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_boost_strength.jpg',
     'Prerequisites': [],
     'Cost': 2}
    AGILITY_BOOST = {'PerkType': 2,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'MeleeWeapon'],
                     [COMBAT, 'CloseCombat'],
                     [SURVIVAL, 'Camouflage'],
                     [SURVIVAL, 'StealthMoving'],
                     [SURVIVAL, 'TracelessMoving'],
                     [SURVIVAL, 'Reaction'],
                     [OTHER, 'Neatness'],
                     [OTHER, 'LootHiding']],
     'Type': PERK_TYPE_STAT_BOOST,
     'BoostedStat': 'Agility',
     'Value': 1,
     'NeedSkillValue': 50,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_boost_agility.jpg',
     'Prerequisites': [],
     'Cost': 2}
    PERCEPTION_BOOST = {'PerkType': 3,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'LightWeapon'],
                     [COMBAT, 'AssaultRifles'],
                     [COMBAT, 'Rifles'],
                     [SURVIVAL, 'Tracking'],
                     [SURVIVAL, 'Spotting'],
                     [SURVIVAL, 'Scouting']],
     'Type': PERK_TYPE_STAT_BOOST,
     'BoostedStat': 'Perception',
     'Value': 1,
     'NeedSkillValue': 50,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_boost_perception.jpg',
     'Prerequisites': [],
     'Cost': 2}
    INTELLIGENCE_BOOST = {'PerkType': 4,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'Explosions'],
                     [SURVIVAL, 'AnomalySpotting'],
                     [OTHER, 'PickLockDisarm'],
                     [OTHER, 'Medicine'],
                     [OTHER, 'Repair'],
                     [OTHER, 'Modification'],
                     [OTHER, 'Identify']],
     'Type': PERK_TYPE_STAT_BOOST,
     'BoostedStat': 'Intelligence',
     'Value': 1,
     'NeedSkillValue': 50,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_boost_intelligence.jpg',
     'Prerequisites': [],
     'Cost': 2}
    ENDURANCE_BOOST = {'PerkType': 5,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'ShootingOnMove'], [SURVIVAL, 'Metabolism']],
     'Type': PERK_TYPE_STAT_BOOST,
     'BoostedStat': 'Endurance',
     'Value': 1,
     'NeedSkillValue': 50,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_boost_endurance.jpg',
     'Prerequisites': [],
     'Cost': 2}
    PSY_BOOST = {'PerkType': 6,
     'Repeatable': 0,
     'MasterSkill': [[SURVIVAL, 'Telepaty']],
     'Type': PERK_TYPE_STAT_BOOST,
     'BoostedStat': 'Psy',
     'Value': 1,
     'NeedSkillValue': 50,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_boost_psy.jpg',
     'Prerequisites': [],
     'Cost': 2}
    STAT_BOOT_PERKS = {STRENGTH_BOOST['BoostedStat']: STRENGTH_BOOST,
     AGILITY_BOOST['BoostedStat']: AGILITY_BOOST,
     PERCEPTION_BOOST['BoostedStat']: PERCEPTION_BOOST,
     INTELLIGENCE_BOOST['BoostedStat']: INTELLIGENCE_BOOST,
     ENDURANCE_BOOST['BoostedStat']: ENDURANCE_BOOST,
     PSY_BOOST['BoostedStat']: PSY_BOOST}
    STAT_BOOT_PERKS_ID = {STRENGTH_BOOST['PerkType']: STRENGTH_BOOST,
     AGILITY_BOOST['PerkType']: AGILITY_BOOST,
     PERCEPTION_BOOST['PerkType']: PERCEPTION_BOOST,
     INTELLIGENCE_BOOST['PerkType']: INTELLIGENCE_BOOST,
     ENDURANCE_BOOST['PerkType']: ENDURANCE_BOOST,
     PSY_BOOST['PerkType']: PSY_BOOST}
    VISIBILITY_REDUCE_HEAVY_WEAPON = {'PerkType': 7,
     'Repeatable': 0,
     'MasterSkill': [[SURVIVAL, 'Camouflage']],
     'Type': PERK_TYPE_SECONDARY_BOOST,
     'BoostedStat': 'Visibility',
     'Value': 0.2,
     'NeedSkillValue': 50,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_boost_agility.jpg',
     'Prerequisites': [],
     'Cost': 1}
    VISIBILITY_REDUCE_HEAVY_LOAD = {'PerkType': 8,
     'Repeatable': 0,
     'MasterSkill': [[SURVIVAL, 'Camouflage']],
     'Type': PERK_TYPE_SECONDARY_BOOST,
     'BoostedStat': 'Visibility',
     'Value': 0.5,
     'NeedSkillValue': 30,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_boost_agility.jpg',
     'Prerequisites': [],
     'Cost': 1}
    STAMINA_USAGE_REDUCE = {'PerkType': 9,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'WeaponTransfer']],
     'Type': PERK_TYPE_SECONDARY_BOOST,
     'BoostedStat': 'StaminaUsage',
     'Value': 0.2,
     'NeedSkillValue': 20,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_weapon-transfer_stamina.jpg',
     'Prerequisites': [],
     'VisualValue': 20,
     'Cost': 1}
    MAX_WEIGHT_ADDON = {'PerkType': 20,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Packing']],
     'Type': PERK_TYPE_SECONDARY_BOOST,
     'BoostedStat': 'MaxWeight',
     'Value': 10,
     'NeedSkillValue': 60,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_packing_weight-addon.jpg',
     'Prerequisites': [],
     'Cost': 1}
    STUN_RESISTANCE = {'PerkType': 21,
     'Repeatable': 0,
     'MasterSkill': [[SURVIVAL, 'Sportsmanship']],
     'Type': PERK_TYPE_SECONDARY_BOOST,
     'BoostedStat': 'StunResisitance',
     'Value': 0.8,
     'NeedSkillValue': 40,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_sportsmanship_stun-resist.jpg',
     'Prerequisites': [],
     'VisualValue': 20,
     'Cost': 1}
    PHYSICAL_RESISTANCE = {'PerkType': 29,
     'Repeatable': 0,
     'MasterSkill': [[SURVIVAL, 'Sportsmanship']],
     'Type': PERK_TYPE_SECONDARY_BOOST,
     'BoostedStat': 'PhysicalResisitance',
     'Value': 0.8,
     'NeedSkillValue': 30,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_sportsmanship_physical-resist.jpg',
     'Prerequisites': [],
     'VisualValue': 20,
     'Cost': 1}
    MOVE_SPEED_UP = {'PerkType': 30,
     'Repeatable': 0,
     'MasterSkill': [[SURVIVAL, 'Sportsmanship']],
     'Type': PERK_TYPE_SECONDARY_BOOST,
     'BoostedStat': 'MoveSpeed',
     'Value': 1.05,
     'NeedSkillValue': 10,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_sportsmanship_speed.jpg',
     'Prerequisites': [],
     'VisualValue': 5,
     'Cost': 1}
    SECONDARY_BOOST_PERKS = {MAX_WEIGHT_ADDON['PerkType']: MAX_WEIGHT_ADDON,
     STUN_RESISTANCE['PerkType']: STUN_RESISTANCE,
     PHYSICAL_RESISTANCE['PerkType']: PHYSICAL_RESISTANCE,
     MOVE_SPEED_UP['PerkType']: MOVE_SPEED_UP,
     VISIBILITY_REDUCE_HEAVY_WEAPON['PerkType']: VISIBILITY_REDUCE_HEAVY_WEAPON,
     VISIBILITY_REDUCE_HEAVY_LOAD['PerkType']: VISIBILITY_REDUCE_HEAVY_LOAD}
    RIFLE_WEIGHT_REDUCE = {'PerkType': 10,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'WeaponTransfer']],
     'Type': PERK_TYPE_WEIGHT_REDUCERS,
     'AffectedItems': [[ItemsCatalog.WEAPON, ItemsCatalog.RIFLE], [ItemsCatalog.WEAPON, ItemsCatalog.SHOTGUN], [ItemsCatalog.WEAPON, ItemsCatalog.SNIPER_RIFLE]],
     'Value': 0.7,
     'NeedSkillValue': 30,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_boost_agility.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    HEAVY_WEAPON_WEIGHT_REDUCE = {'PerkType': 11,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'WeaponTransfer']],
     'Type': PERK_TYPE_WEIGHT_REDUCERS,
     'AffectedItems': [[ItemsCatalog.WEAPON, ItemsCatalog.MACHINE_GUN], [ItemsCatalog.WEAPON, ItemsCatalog.GRENADE_LAUNCHER], [ItemsCatalog.WEAPON, ItemsCatalog.ROCKET_LAUNCHER]],
     'Value': 0.7,
     'NeedSkillValue': 40,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_boost_agility.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    WEIGHT_REDUCERS_PERKS = {RIFLE_WEIGHT_REDUCE['PerkType']: RIFLE_WEIGHT_REDUCE,
     HEAVY_WEAPON_WEIGHT_REDUCE['PerkType']: HEAVY_WEAPON_WEIGHT_REDUCE}
    LIGHT_WEAPON_RELOAD_TIME_REDUCE = {'PerkType': 12,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'LightWeapon']],
     'Type': PERK_TYPE_RELOAD_TIME_REDUCERS,
     'AffectedItems': [ItemsCatalog.PISTOL, ItemsCatalog.REVOLVER],
     'Value': 1.3,
     'NeedSkillValue': 20,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_light-weapons_reload-time.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    ASSAULT_RIFLES_RELOAD_TIME_REDUCE = {'PerkType': 13,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'AssaultRifles']],
     'Type': PERK_TYPE_RELOAD_TIME_REDUCERS,
     'AffectedItems': [ItemsCatalog.ASSAULT_RIFLE, ItemsCatalog.SUB_MACHINE_GUN],
     'Value': 1.3,
     'NeedSkillValue': 20,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_assault-rifles_reload-time.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    RIFLES_RELOAD_TIME_REDUCE = {'PerkType': 14,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'Rifles']],
     'Type': PERK_TYPE_RELOAD_TIME_REDUCERS,
     'AffectedItems': [ItemsCatalog.RIFLE, ItemsCatalog.SHOTGUN, ItemsCatalog.SNIPER_RIFLE],
     'Value': 1.3,
     'NeedSkillValue': 20,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_rifles_reload-time.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    HEAVY_WEAPON_RELOAD_TIME_REDUCE = {'PerkType': 15,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'HeavyWeapon']],
     'Type': PERK_TYPE_RELOAD_TIME_REDUCERS,
     'AffectedItems': [ItemsCatalog.MACHINE_GUN, ItemsCatalog.GRENADE_LAUNCHER, ItemsCatalog.ROCKET_LAUNCHER],
     'Value': 1.3,
     'NeedSkillValue': 20,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_heavy-weapons_reload-time.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    RELOAD_TIME_REDUCERS_PERKS = {LIGHT_WEAPON_RELOAD_TIME_REDUCE['PerkType']: LIGHT_WEAPON_RELOAD_TIME_REDUCE,
     ASSAULT_RIFLES_RELOAD_TIME_REDUCE['PerkType']: ASSAULT_RIFLES_RELOAD_TIME_REDUCE,
     RIFLES_RELOAD_TIME_REDUCE['PerkType']: RIFLES_RELOAD_TIME_REDUCE,
     HEAVY_WEAPON_RELOAD_TIME_REDUCE['PerkType']: HEAVY_WEAPON_RELOAD_TIME_REDUCE}
    LIGHT_WEAPON_EQIUP_TIME_REDUCE = {'PerkType': 16,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'LightWeapon']],
     'Type': PERK_TYPE_EQUIP_TIME_REDUCERS,
     'AffectedItems': [ItemsCatalog.PISTOL, ItemsCatalog.REVOLVER],
     'Value': 0.3,
     'NeedSkillValue': 10,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_light-weapons_equip-time.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    ASSAULT_RIFLES_EQIUP_TIME_REDUCE = {'PerkType': 17,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'AssaultRifles']],
     'Type': PERK_TYPE_EQUIP_TIME_REDUCERS,
     'AffectedItems': [ItemsCatalog.ASSAULT_RIFLE, ItemsCatalog.SUB_MACHINE_GUN],
     'Value': 0.7,
     'NeedSkillValue': 10,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_assault-rifles_equip-time.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    RIFLES_EQIUP_TIME_REDUCE = {'PerkType': 18,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'Rifles']],
     'Type': PERK_TYPE_EQUIP_TIME_REDUCERS,
     'AffectedItems': [ItemsCatalog.RIFLE, ItemsCatalog.SHOTGUN, ItemsCatalog.SNIPER_RIFLE],
     'Value': 0.7,
     'NeedSkillValue': 10,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_rifles_equip-time.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    HEAVY_WEAPON_EQIUP_TIME_REDUCE = {'PerkType': 19,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'HeavyWeapon']],
     'Type': PERK_TYPE_EQUIP_TIME_REDUCERS,
     'AffectedItems': [ItemsCatalog.MACHINE_GUN, ItemsCatalog.GRENADE_LAUNCHER, ItemsCatalog.ROCKET_LAUNCHER],
     'Value': 0.7,
     'NeedSkillValue': 10,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_heavy-weapons_equip-time.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    EQUIP_TIME_REDUCERS_PERKS = {LIGHT_WEAPON_EQIUP_TIME_REDUCE['PerkType']: LIGHT_WEAPON_EQIUP_TIME_REDUCE,
     ASSAULT_RIFLES_EQIUP_TIME_REDUCE['PerkType']: ASSAULT_RIFLES_EQIUP_TIME_REDUCE,
     RIFLES_EQIUP_TIME_REDUCE['PerkType']: RIFLES_EQIUP_TIME_REDUCE,
     HEAVY_WEAPON_EQIUP_TIME_REDUCE['PerkType']: HEAVY_WEAPON_EQIUP_TIME_REDUCE}
    MORE_GRENADES = {'PerkType': 23,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'Throwing']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'MaxGrenades',
     'Value': 1,
     'NeedSkillValue': 30,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_throw_fast.jpg',
     'Prerequisites': [],
     'Cost': 1}
    REPAIR_LOW_LEVEL = {'PerkType': 24,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Repair']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'RepairLevel',
     'Value': 1,
     'NeedSkillValue': 10,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_repair_simple-level.jpg',
     'Prerequisites': [],
     'Cost': 1}
    REPAIR_MEDIUM_LEVEL = {'PerkType': 25,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Repair']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'RepairLevel',
     'Value': 1,
     'NeedSkillValue': 40,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_repair_medium-level.jpg',
     'Prerequisites': [REPAIR_LOW_LEVEL['PerkType']],
     'Cost': 1}
    REPAIR_HIGH_LEVEL = {'PerkType': 26,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Repair']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'RepairLevel',
     'Value': 1,
     'NeedSkillValue': 70,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_repair_hard-level.jpg',
     'Prerequisites': [REPAIR_MEDIUM_LEVEL['PerkType']],
     'Cost': 1}
    REPAIR_ALL_LEVEL = {'PerkType': 27,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Repair']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'RepairLevel',
     'Value': 1,
     'NeedSkillValue': 80,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_repair_best-level.jpg',
     'Prerequisites': [REPAIR_HIGH_LEVEL['PerkType']],
     'Cost': 1}
    LIGHT_WEAPON_NEATNESS = {'PerkType': 32,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Neatness']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'NeatnessWeapon',
     'Value': 1,
     'NeedSkillValue': 0,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_neatness_light-weapons.jpg',
     'Prerequisites': [],
     'Cost': 1}
    ASSAULT_RIFLE_NEATNESS = {'PerkType': 33,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Neatness']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'NeatnessWeapon',
     'Value': 1,
     'NeedSkillValue': 20,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_neatness_assault-rifles.jpg',
     'Prerequisites': [],
     'Cost': 1}
    RIFLES_NEATNESS = {'PerkType': 34,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Neatness']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'NeatnessWeapon',
     'Value': 1,
     'NeedSkillValue': 10,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_neatness_rifles.jpg',
     'Prerequisites': [],
     'Cost': 1}
    HEAVY_WEAPON_NEATNESS = {'PerkType': 35,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Neatness']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'NeatnessWeapon',
     'Value': 1,
     'NeedSkillValue': 30,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_neatness_heavy-weapons.jpg',
     'Prerequisites': [],
     'Cost': 1}
    MEDICINE_ADDON = {'PerkType': 28,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Medicine']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'MedicineUp',
     'Value': 0.2,
     'NeedSkillValue': 40,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_medicine_addon.jpg',
     'Prerequisites': [],
     'VisualValue': 20,
     'Cost': 2}
    BATTLE_DOCTOR = {'PerkType': 45,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Medicine']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'MedicineUp',
     'Value': 0.4,
     'NeedSkillValue': 60,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_medicine_doctor.jpg',
     'Prerequisites': [],
     'VisualValue': 40,
     'Cost': 2}
    DEBUFF_NIHILIZER = {'PerkType': 31,
     'Repeatable': 0,
     'MasterSkill': [[SURVIVAL, 'Metabolism']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'DebuffLow',
     'Value': 0.7,
     'NeedSkillValue': 40,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_metabolism_debuff-nihilizer.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    RIFLES_SNIPING = {'PerkType': 36,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'Rifles']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'Sniping',
     'Value': 1,
     'NeedSkillValue': 60,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_rifles_sniping.jpg',
     'Prerequisites': [],
     'Cost': 1}
    THROW_RANGE = {'PerkType': 37,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'Throwing']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'ThrowRange',
     'Value': 0.01,
     'NeedSkillValue': 20,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_throw_range.jpg',
     'Prerequisites': [],
     'Cost': 1}
    WEAPON_DROP_LOWER = {'PerkType': 44,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Luck']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'Drop',
     'Value': 0.3,
     'NeedSkillValue': 40,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_drop-lower_weapon.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    AMMO_DROP_LOWER = {'PerkType': 38,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Luck']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'Drop',
     'Value': 0.3,
     'NeedSkillValue': 30,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_drop-lower_ammo.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    LOOT_DROP_LOWER = {'PerkType': 39,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Luck']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'Drop',
     'Value': 0.3,
     'NeedSkillValue': 60,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_drop-lower_loot.jpg',
     'Prerequisites': [],
     'VisualValue': 30,
     'Cost': 1}
    CRAFT_LOW_LEVEL = {'PerkType': 40,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Modification']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'RepairLevel',
     'Value': 1,
     'NeedSkillValue': 10,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_modification_simple-level.jpg',
     'Prerequisites': [],
     'Cost': 1}
    CRAFT_MEDIUM_LEVEL = {'PerkType': 41,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Modification']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'RepairLevel',
     'Value': 1,
     'NeedSkillValue': 40,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_modification_medium-level.jpg',
     'Prerequisites': [CRAFT_LOW_LEVEL['PerkType']],
     'Cost': 1}
    CRAFT_HIGH_LEVEL = {'PerkType': 42,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Modification']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'RepairLevel',
     'Value': 1,
     'NeedSkillValue': 70,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_modification_hard-level.jpg',
     'Prerequisites': [CRAFT_MEDIUM_LEVEL['PerkType']],
     'Cost': 1}
    CRAFT_ALL_LEVEL = {'PerkType': 43,
     'Repeatable': 0,
     'MasterSkill': [[OTHER, 'Modification']],
     'Type': GAMEPLAY_CHANGERS,
     'BoostedStat': 'RepairLevel',
     'Value': 1,
     'NeedSkillValue': 100,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_modification_best-level.jpg',
     'Prerequisites': [CRAFT_HIGH_LEVEL['PerkType']],
     'Cost': 1}
    GAMEPLAY_CHANGERS_PERKS = {MORE_GRENADES['PerkType']: MORE_GRENADES,
     REPAIR_LOW_LEVEL['PerkType']: REPAIR_LOW_LEVEL,
     REPAIR_MEDIUM_LEVEL['PerkType']: REPAIR_MEDIUM_LEVEL,
     REPAIR_HIGH_LEVEL['PerkType']: REPAIR_HIGH_LEVEL,
     REPAIR_ALL_LEVEL['PerkType']: REPAIR_ALL_LEVEL,
     MEDICINE_ADDON['PerkType']: MEDICINE_ADDON,
     DEBUFF_NIHILIZER['PerkType']: DEBUFF_NIHILIZER,
     LIGHT_WEAPON_NEATNESS['PerkType']: LIGHT_WEAPON_NEATNESS,
     ASSAULT_RIFLE_NEATNESS['PerkType']: ASSAULT_RIFLE_NEATNESS,
     RIFLES_NEATNESS['PerkType']: RIFLES_NEATNESS,
     HEAVY_WEAPON_NEATNESS['PerkType']: HEAVY_WEAPON_NEATNESS,
     RIFLES_SNIPING['PerkType']: RIFLES_SNIPING,
     THROW_RANGE['PerkType']: THROW_RANGE,
     WEAPON_DROP_LOWER['PerkType']: WEAPON_DROP_LOWER,
     AMMO_DROP_LOWER['PerkType']: AMMO_DROP_LOWER,
     LOOT_DROP_LOWER['PerkType']: LOOT_DROP_LOWER,
     CRAFT_LOW_LEVEL['PerkType']: CRAFT_LOW_LEVEL,
     CRAFT_MEDIUM_LEVEL['PerkType']: CRAFT_MEDIUM_LEVEL,
     CRAFT_HIGH_LEVEL['PerkType']: CRAFT_HIGH_LEVEL,
     CRAFT_ALL_LEVEL['PerkType']: CRAFT_ALL_LEVEL,
     BATTLE_DOCTOR['PerkType']: BATTLE_DOCTOR}
    CRIT_VALUE_LVL1 = {'PerkType': 45,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'Rifles']],
     'Type': CRIT_DAMAGE,
     'BoostedStat': 'Critical',
     'Value': 0.1,
     'VisualValue': 10,
     'NeedSkillValue': 40,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_critical_value_1.jpg',
     'Prerequisites': [],
     'Cost': 1}
    CRIT_VALUE_LVL2 = {'PerkType': 46,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'ShootingOnMove']],
     'Type': CRIT_DAMAGE,
     'BoostedStat': 'Critical',
     'Value': 0.1,
     'VisualValue': 10,
     'NeedSkillValue': 40,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_critical_value_2.jpg',
     'Prerequisites': [],
     'Cost': 1}
    CRIT_VALUE_LVL3 = {'PerkType': 47,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'ShootingOnMove']],
     'Type': CRIT_DAMAGE,
     'BoostedStat': 'Critical',
     'Value': 0.4,
     'VisualValue': 40,
     'NeedSkillValue': 70,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_critical_value_3.jpg',
     'Prerequisites': [],
     'Cost': 1}
    CRIT_VALUE_LVL4 = {'PerkType': 48,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'Rifles']],
     'Type': CRIT_DAMAGE,
     'BoostedStat': 'Critical',
     'Value': 0.4,
     'VisualValue': 40,
     'NeedSkillValue': 70,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_critical_value_4.jpg',
     'Prerequisites': [],
     'Cost': 2}
    CRIT_CHANCE_LVL1 = {'PerkType': 49,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'HeavyWeapon']],
     'Type': CRIT_CHANCE,
     'BoostedStat': 'Critical',
     'Value': 0.05,
     'VisualValue': 5,
     'NeedSkillValue': 30,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_critical_chance_1.jpg',
     'Prerequisites': [],
     'Cost': 1}
    CRIT_CHANCE_LVL2 = {'PerkType': 50,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'HeavyWeapon']],
     'Type': CRIT_CHANCE,
     'BoostedStat': 'Critical',
     'Value': 0.08,
     'VisualValue': 8,
     'NeedSkillValue': 40,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_critical_chance_2.jpg',
     'Prerequisites': [],
     'Cost': 1}
    CRIT_CHANCE_LVL3 = {'PerkType': 51,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'HeavyWeapon']],
     'Type': CRIT_CHANCE,
     'BoostedStat': 'Critical',
     'Value': 0.09,
     'VisualValue': 9,
     'NeedSkillValue': 60,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_critical_chance_3.jpg',
     'Prerequisites': [],
     'Cost': 1}
    CRIT_CHANCE_LVL4 = {'PerkType': 52,
     'Repeatable': 0,
     'MasterSkill': [[COMBAT, 'HeavyWeapon']],
     'Type': CRIT_CHANCE,
     'BoostedStat': 'Critical',
     'Value': 0.08,
     'VisualValue': 8,
     'NeedSkillValue': 70,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_critical_chance_4.jpg',
     'Prerequisites': [],
     'Cost': 2}
    DAMAGE_BOOSTERS = {CRIT_VALUE_LVL1['PerkType']: CRIT_VALUE_LVL1,
     CRIT_VALUE_LVL2['PerkType']: CRIT_VALUE_LVL2,
     CRIT_VALUE_LVL3['PerkType']: CRIT_VALUE_LVL3,
     CRIT_VALUE_LVL4['PerkType']: CRIT_VALUE_LVL4,
     CRIT_CHANCE_LVL1['PerkType']: CRIT_CHANCE_LVL1,
     CRIT_CHANCE_LVL2['PerkType']: CRIT_CHANCE_LVL2,
     CRIT_CHANCE_LVL3['PerkType']: CRIT_CHANCE_LVL3,
     CRIT_CHANCE_LVL4['PerkType']: CRIT_CHANCE_LVL4}
    SUPER_PERK = {'PerkType': 999,
     'Repeatable': 0,
     'MasterSkill': [],
     'Type': SUPERPERK,
     'BoostedStat': '',
     'Value': 0,
     'NeedSkillValue': 80,
     'IconName': 'soGUI/maps/Icons/ability/icon_perk_boost_agility.jpg',
     'Prerequisites': [],
     'Cost': 1}
    ALL_PERKS = {}
    ALL_PERKS.update(STAT_BOOT_PERKS_ID.items())
    ALL_PERKS.update(SECONDARY_BOOST_PERKS.items())
    ALL_PERKS.update(WEIGHT_REDUCERS_PERKS.items())
    ALL_PERKS.update(RELOAD_TIME_REDUCERS_PERKS.items())
    ALL_PERKS.update(EQUIP_TIME_REDUCERS_PERKS.items())
    ALL_PERKS.update(GAMEPLAY_CHANGERS_PERKS.items())
    ALL_PERKS.update(DAMAGE_BOOSTERS.items())

    def GetPerkByID(self, id):
        return self.ALL_PERKS[id]


PerkCatalog = PerkList()