# Embedded file name: scripts/common/PPData.py
PP_TYPE_RADIATION_VAR1 = 0
PP_TYPE_ACID_VAR1 = 10
PP_TYPE_ACID_VAR2 = 11
PP_TYPE_ELECTRICITY_VAR1 = 20
PP_TYPE_ELECTRICITY_VAR2 = 21
PP_TYPE_ELECTRICITY_VAR3 = 22
PP_TYPE_FIRE_VAR1 = 30
PP_TYPE_FIRE_VAR2 = 31
PP_TYPE_FIRE_VAR3 = 32
PP_TYPE_PSIONICS_VAR1 = 40
PP_TYPE_GRAVITATIONAL_VAR1 = 50
PP_TYPE_GRAVITATIONAL_VAR2 = 51