# Embedded file name: scripts/common/Quest.py
"""
Created on 03.02.2011

@author: Madcat
"""
NO_QUEST_ID = 0
DEL_DEFAULT = 0
DEL_ONWIN = 1
DEL_ONFAILED = 2
TYPE_FARM = 0
TYPE_FARM_AUTO = 16
TYPE_TALK = 1
TYPE_KILLMOBS_WITH_ONTEST = 2
TYPE_KILLMOBS = 3
TYPE_AREA_DISCOVER = 4
TYPE_MONEYBACK = 5
TYPE_TRIGGER_ACTION = 6
TYPE_QITEM_USE = 7
TYPE_AREA_LEAVE = 8
TYPE_TIMER = 9
TYPE_DIE = 17
TYPE_GAME_EXIT = 18
TYPE_ITEM_EQIP = 19
TYPE_ITEM_ADD = 20
TUTORQUESTS = range(200, 207)
TYPE_TUT_FIRE = 201
TYPE_TUT_HEAL = 202
TYPE_TUT_ITEM_REPAIR = 203
TYPE_TUT_LIGHT = 204
TYPE_TUT_GUI = 206
CONTENTQUESTS = range(10, 16)
TYPE_COMP_COMPLETE_ALL = 10
TYPE_COMP_COMPLETE_ALL_IN_ORDER = 11
TYPE_COMP_COMPLETE_ONE_AT_CHOICE = 12
TYPE_COMP_COMPLETE_ALL_WITH_ONTEST = 13
TYPE_COMP_COMPLETE_ALL_IN_ORDER_WITH_ONTEST = 14
TYPE_COMP_COMPLETE_ONE_AT_CHOICE_WITH_ONTEST = 15
TYPE_PVP_COMMAND_DEATHMATCH = 100
TYPE_PLAYING_WITH_DIRECTOR = 50
GROUP_QUEST = 1
GROUP_REGISTRATION = 2
STATE_OPENED = 0
STATE_CLOSED = 1
STATE_ONTEST = 2
STATE_FREEZ = 3
STATE_FAILED = 4
STATE_INFO = 5
STARTTALKQUESTS = 2500
ENDTALKQUESTS = 3500
QUEUE_NONE = 0
QUEUE_GROUP = 1
QUEUE_ANDONE = 2
QUEUE_GROUP_ANDONE = 3
JOURNAL_PROCESS = 0
JOURNAL_COMPLETED = 1
JOURNAL_BOTH = 2
JOURNAL_ID_NEXT = 'next'

def checkDialog(questID):
    if questID < STARTTALKQUESTS or questID > ENDTALKQUESTS:
        return True
    return False


STATE_GROUP_QUEST_IDLE = 0
STATE_GROUP_QUEST_AGREE = 1
STATE_GROUP_QUEST_DISAGREE = 7
STATE_GROUP_QUEST_TAKED = 2
STATE_GROUP_QUEST_OPENED = 3
STATE_GROUP_QUEST_CELL_LOAD = 4
STATE_GROUP_QUEST_COMPLETE = 5
STATE_GROUP_QUEST_FAILED = 6
STATE_GROUP_QUEST_LEAVED = 8
SHOW_MESSAGE_TAKE = 1
SHOW_MESSAGE_CLOSE = 2
SHOW_MESSAGE_PROGRESS = 4
SHOW_JOURNAL = 8
SHOW_ONWIN = 16
SHOW_ONFAILED = 32
SHOW_TUTORIAL = 64
STATUS_CLOSED = 1
STATUS_FAILED = 0
STATUS_SUCCESSFULL_COLLECT_ITEMS = 2
STATUS_ONPROCESS_COLLECT_ITEMS = 3
STATUS_FAILED_COLLECT_ITEMS = 4
STATUS_SUCCESSFULL_KILLED_CREATURE = 5
STATUS_ONPROCESS_KILLED_CREATURE = 6
STATUS_NEED_MORE_MONEY = 7
STATUS_AREA_FOUNDED = 8
STATUS_CANT_TELEPORT_TO_INSTANCE = 9
STATUS_NO_FREE_INSTANCE = 10
STATUS_ONWIN = 11
STATUS_ONFAILED = 12
STATUS_JOURNAL_RENEW = 13
STATUS_OPENED = 14
STATUS_WIPE_OVER = 15
STATUS_NPC_IS_TOO_FAR = 16
STATUS_CANT_TAKE_MISSION_NOW = 17
PKEY_NUMOFOBJ = 0
PKEY_NAMEOFOBJ = 1
PKEY_TYPEOFOBJ = 2
PKEY_NPCS = 3