# Embedded file name: scripts/common/Config/Creatures/Constants.py


class BrainStates:
    ATTACK_NO_TARGET, ATTACK_COOLDOWN, ATTACK_SUCCESS, ATTACK_TOO_FAR, GO_PROMENADE, GO_NEXT_WAYPOINT, FOLLOW_TARGET, DEAD = xrange(8)


SUBTYPE_NAME = 'subtype_name'
SUBTYPE_INDEX_BY_NAME = '__subtype_index_by_name__'

class KEYWORDS:
    BYLEVEL = 'bylevel'
    FULL_OVERRIDE = 'override'
    DEFAULT_LEVEL = 'default'
    APPEND = 'append'
    PREPEND = 'prepend'
    PARENT = 'parent='


NAME = 'name'
HEALTH = 'health'
TINTS = 'tints'
COEF_LEVEL = 'coefLevel'
EXPERIENCE = 'experience'
KARMA = 'karma'
AGRO_RANGE = 'agro_range'
LOSE_AGRO_RANGE = 'lose_agro_range'
GCD = 'global_cooldown'
DEFAULT_STATE = 'default_state'
MODEL = 'model'
COLLIDERS = 'colliders'
MODEL_SCALE = 'model_scale'
FOOT_NODES = 'foot_nodes'
STATES = 'states'
COMMON_CONDITIONS = 'common_conditions'
ACTIONS = 'actions'
DEFENCE = 'defence'
HEIGHT = 'height'
WIDTH = 'width'
DECOMPOSE_TIME = 'decompose_time'
LOOT = 'loot'
FOOTSTEPS_SOUND = 'footsteps_sound'
EVENTS = 'events'
MELEE_DISTANCE = 'melee_distance'
MELEE_HEIGHT = 'melee_height'
SKILLS = 'skills'
EV_ON_TAKE_DAMAGE = 'onTakeDamage'
ACT_MODEL_ACTIONS = 'model_actions'
ACT_SOUNDS = 'sounds'
ACT_SFXES = 'sfxes'
STATE_SPEED = 'speed'
STATE_SKILLS = 'skills'
STATE_CONDITIONS = 'conditions'
STATE_TIMER, STATE_TIMER_TIME, STATE_TIMER_STATE = ('change_state_timer', 0, 1)
SKILL_INDEX = 'index'
SKILL_TYPE = 'type'
SKILL_NAME = 'name'
SKILL_CAST_RANGE = 'cast_range'
SKILL_AOE_RADIUS = 'aoe_radius'
SKILL_COOLDOWN = 'cooldown'
SKILL_ACTIONS = 'actions'
SKILL_DAMAGE = 'damage'
SKILL_EFFECTS = 'effects'
SKILL_SELF_SFXES = 'self_sfxes'
SKILL_TARGET_SFXES = 'target_sfxes'
SKILL_THROW_TYPE = 'throwing_type'
SKILL_EXPLODE_DELAY = 'explode_delay'
SKILL_THROW_START_POS = 'throw_start_position'
DMG_BODY_ZONES = 'body_zones'
DMG_TYPE = 'type'
DMG_PENETRATION = 'penetration'
DMG_VALUE = 'value'
MOVE_TYPE_FOLLOW = 'follow_target'
MOVE_TYPE_WALK_AROUND = 'walk_around'