# Embedded file name: scripts/common/gui_const/CHAR_MAKER.py
STAGE_1 = 0
STAGE_2 = 1
STAGE_3 = 2
EVENT_STAGESWITCH = 0
EVENT_APPEARANCE = 1
EVENT_GENDER_CHOICE = 2
EVENT_ORIGINATION_CHOICE = 3
EVENT_CANCEL = 4
EVENT_FINISH = 5
EVENT_NICKNAME = 6
GENDER_MALE = 0
GENDER_FEMALE = 1
ORIGINATION_LOCALS = 0
ORIGINATION_FOREIGNERS = 1
HINT_TYPE_NORMAL = 0
HINT_TYPE_ERROR = 1
HINT_TYPE_OK = 2