# Embedded file name: scripts/common/gui_const/CHAR_PICKER.py
EVENT_SELECT = 0
EVENT_NEW = 1
EVENT_DELETE = 2
EVENT_PLAY = 3
EVENT_BACK = 4
EVENT_USE = 5
EVENT_MODELPAN = 6
EVENT_RESTORE = 7
EVENT_PREMIUM = 8
SLOT_STATE_SELECTED = 0
SLOT_STATE_EMPTY = 1
SLOT_STATE_DELETED = 2