# Embedded file name: scripts/common/gui_const/CHAT_CONSOLE.py
TAB_ALL, TAB_CLAN, TAB_PARTY, TAB_PRIVATE, TAB_FRIENDS = xrange(5)
EVENT_SEND = 0
EVENT_SETTINGS = 1
EVENT_REPEAT = 2
MESSAGE_DAMAGE = 1
MESSAGE_ITEMS = 2
MESSAGE_SYSTEM = 8
MESSAGE_QUEST = 16
MESSAGE_NPC = 64
MESSAGE_GENERAL = 128
MESSAGE_CLAN = 256
MESSAGE_PARTY = 512
MESSAGE_PRIVATE = 1024
MESSAGE_FRIENDS = 2048
MESSAGE_TRADE = 4096
MESSAGE_ALL = MESSAGE_DAMAGE | MESSAGE_ITEMS | MESSAGE_SYSTEM | MESSAGE_SYSTEM | MESSAGE_QUEST | MESSAGE_NPC | MESSAGE_GENERAL | MESSAGE_CLAN | MESSAGE_PARTY | MESSAGE_PRIVATE | MESSAGE_FRIENDS | MESSAGE_TRADE