# Embedded file name: scripts/common/gui_const/GUI_ID.py
GUI_ID_NONE = 0
GUI_ID_LOGIN = 1
GUI_ID_OPTIONS = 2
GUI_ID_SERVERLIST = 3
GUI_ID_CHARSELECT = 4
GUI_ID_CHARCREATE = 5
GUI_ID_INVENTORY = 6
GUI_ID_NPCTRADE = 7
GUI_ID_DIALOGUE = 8
GUI_ID_PCTRADE = 9
GUI_ID_CHARSCREEN = 10
GUI_ID_PDAMAIN = 11
GUI_ID_GPSMAP = GUI_ID_PDAMAP = 12
GUI_ID_PDAPEDIA = 13
GUI_ID_PDARECIPES = 14
GUI_ID_PDAGUILD = 15
GUI_ID_QUESTLOG = GUI_ID_PDAQUEST = 16
GUI_ID_EFFECTSFRAME = 17
GUI_ID_SKILLS = 18
GUI_ID_ITEMCACHE = 19
GUI_ID_PRIVATESTORE = 20
GUI_ID_TUTORIAL = 21
GUI_ID_PLAYERMANUAL = 22
GUI_ID_PACKAGESELL = 23
GUI_ID_ACTIONBAR = 24
GUI_ID_PVPSTATS = 25
GUI_ID_REPSTATS = 26
GUI_ID_PARTYFRAMES = 27
GUI_ID_PLAYERFRAME = 28
GUI_ID_NAMEPLATES = 29
GUI_ID_BASECAPTURE = 30
GUI_ID_MAGNETLOCKQTE = 31
GUI_ID_CRAFT = 32
GUI_ID_INGAMEMENU = 33
GUI_ID_OBJECTIVETRACKER = 34
GUI_ID_CHATCONSOLE = 35
GUI_ID_OPTIONS_NEW = 36