# Embedded file name: scripts/common/gui_const/INVENTORY.py
EVENT_ACTION = 0
EVENT_DROP = 1
EVENT_MOVE = 2
EVENT_EQUIP = 3
EVENT_TOQUICKBAR = 4
EVENT_REPAIR = 5
EVENT_CONTEXT = 6
EVENT_FILTERCHANGE = 7
EVENT_DELETE = 8
FILTER_WEAPON = 1
FILTER_CONSUMABLE = 2
FILTER_ARMOR = 4
FILTER_MISC = 8
FILTER_QUEST = 16
FILTER_ARTIFACT = 32
FILTER_GOLD = 64