# Embedded file name: scripts/common/gui_const/ITEM_CACHE.py
EVENT_TAKE = 0
EVENT_GIVE = 1
EVENT_FILTERCHANGE = 2
FILTER_WEAPON = 1
FILTER_CONSUMABLE = 2
FILTER_ARMOR = 4
FILTER_MISC = 8
FILTER_QUEST = 16
FILTER_ARTIFACT = 32