# Embedded file name: scripts/common/gui_const/PACKAGE_SELL.py
EVENT_PACKSELECT = 0
EVENT_ITEMADD = 1
EVENT_ITEMREMOVE = 2
EVENT_BUY = 3
EVENT_CLEAR = 4
EVENT_AUTOFILL = 5
EVENT_HIDEUNAFFORDABLE = 6
EVENT_ITEMCONTEXT = 7
EVENT_CLOSE = 8
REWARD_ITEM = 0
PAY_ITEM = 1