# Embedded file name: scripts/common/gui_const/PC_TRADE.py
EVENT_CANCEL = 0
EVENT_OFFER = 1
EVENT_CONFIRM = 2
EVENT_CONTEXT = 3
EVENT_MONEYSET = 4
EVENT_ABORT = 5
EVENT_ACTION = 6
EVENT_ADDITEM = 7
EVENT_DELITEM = 8
EVENT_GOLDSET = 9
SOURCE_PLAYER = 0
SOURCE_CONTRACTOR = 1