# Embedded file name: scripts/common/gui_const/QUESTLOG.py
EVENT_SELECT = 0
EVENT_CANCEL = 1
EVENT_SHARE = 2
EVENT_CONTEXT = 3
EVENT_USE = 4
EVENT_LINK = 5
EVENT_TRACK = 6
QUEST_CLASS_NORMAL = 0
QUEST_CLASS_DUMMY = 1
QUEST_STATE_NEW = 0
QUEST_STATE_FAILED = 1
QUEST_STATE_COMPLETED = 2
QUEST_STATE_TRACKED = 3